name: Code Style
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Install Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install Dependencies
      shell: bash -el {0}
      run: |
        pip install tox flake8
    - name: Check Code Style
      run: |
        tox -e codestyle