name: Testing

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:

          - name: latest supported versions
            os: ubuntu-latest
            python-version: '3.10'
            toxenv: python3.10-test-all-latest-cov
            toxposargs: --cov-report=xml:${GITHUB_WORKSPACE}/coverage.xml

          - name: oldest supported versions
            os: ubuntu-latest
            python-version: '3.7'
            toxenv: python3.7-test-oldest

          - name: macOS 11
            os: macos-11
            python-version: '3.10'
            toxenv: python3.10-test-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Conda w/ Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: soliket-tests
          environment-file: soliket-tests.yml
          auto-activate-base: false
          python-version: ${{ matrix.python-version }}
          use-mamba: true
          miniforge-variant: Mambaforge
      - if contains(matrix.os, 'ubuntu')
        name: Install class
        shell: bash -el {0}
        run: |
          pip install classy
        env:
          MATRIX_OS: ${{ matrix.os }}
      - name: Run Tests
        shell: bash -el {0}
        run: |
          tox -e ${{ matrix.toxenv }} ${{ matrix.toxargs }} -- ${{ matrix.toxposargs }}
      - if: contains(matrix.toxenv, '-cov')
        name: Report Coverage
        uses: codecov/codecov-action@v1
