name: Testing

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:

          - name: latest supported versions
            os: ubuntu-latest
            python: '3.10'
            toxenv: py310-test-all-latest-cov
            toxposargs: --cov-report=xml:${GITHUB_WORKSPACE}/coverage.xml

          - name: oldest supported versions
            os: ubuntu-latest
            python: 3.7
            toxenv: py37-test-oldest

          - name: macOS latest supported
            os: macos-latest
            python: '3.10'
            toxenv: py310-test-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install Dependencies
      run: |
        pip install tox
    - name: Install Classy
      run: |
        if [[ ${MATRIX_OS} == "macos-latest" ]]; then
          . ci_scripts/install_class_osx.sh
        else
          . ci_scripts/install_class_linux.sh
        fi
        python -c "import classy; print(classy)"
      env:
        MATRIX_OS: ${{ matrix.os }}
    - name: Run Tests
      run: |
        tox -e ${{ matrix.toxenv }} ${{ matrix.toxargs }} -- ${{ matrix.toxposargs }}
    - if: contains(matrix.toxenv, '-cov')
      name: Report Coverage
      uses: codecov/codecov-action@v1
